services:
  app:
    # Build expects a Dockerfile at repo root (multi-stage Maven/JDK 21).
    build: .
    container_name: insight-app
    ports:
      - "8080:8080"
    environment:
      # Spring profile
      - SPRING_PROFILES_ACTIVE=dev
      # --- Aiven PostgreSQL (application DB: users/roles) ---
      # Copy JDBC URL from Aiven console, keep sslmode=require
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      # --- Metabase embedding (backend needs these to sign tokens) ---
      - METABASE_SITE_URL=${METABASE_SITE_URL}
      - METABASE_EMBEDDING_SECRET_KEY=${METABASE_EMBEDDING_SECRET_KEY}
      # Allow iframe from Metabase origin
      - APP_ORIGIN=${APP_ORIGIN}
    depends_on:
      metabase:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - insight-net

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      # Public URL of Metabase (used in embeds, redirects)
      - MB_SITE_URL=${METABASE_SITE_URL}
      # Allow embedding inside the app origin (iframe)
      - MB_EMBEDDING_APP_ORIGIN=${APP_ORIGIN}
      # --- BigQuery auth (service account) ---
      # Metabase BigQuery driver uses Google ADC; point to the JSON key path
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcp-sa.json
    volumes:
      # Mount the GCP service account JSON read-only
      - ./docker/credentials/gcp-service-account.json:/run/secrets/gcp-sa.json:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/api/health | grep -q 'ok'"]
      interval: 10s
      timeout: 5s
      retries: 12
    restart: unless-stopped
    networks:
      - insight-net

networks:
  insight-net:
    name: insight-net